### ISSUE TITLE
Account creation/refreshing main while logged in should send you to dashboard.

### ISSUE THREAD

**Issue by alexo-a** [TheBobbyLlama/pagebound#11]
If the session is still valid and you go to the localhost main, it seems to realize you're logged in but doesn't take you to dashboard, BUT it does still have the login form, despite me being logged in.
Also, upon successful account creation, I should be brought to the dashboard.

**Comment by TheBobbyLlama** [comment]
As it works now, the user must verify their email before they can log in.  So taking them to the dashboard on account creation doesn't really make sense.
